<a href="https://colab.research.google.com/github/DigoShane/Codes/blob/main/00_TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In  this notebook, we are goign tot cover some of the most fundamental concepts of tensors using tensor flow.

More specifically, we're goignt o cover
*Intro to tensors

*Getting information from tensors

*Manipulating tensors

*Tensors and Numpy

*Using @tf.function (a way to speed up regular python functions)

*Using GPU's with TensorFlow (or TPUs)

*Exercises to try yourself.

Introduction to tensors

In [2]:
#import Tensor Flow
import tensorflow as tf
print(tf.__version__)

2.19.0


In [6]:
#creating tenosrs with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [8]:
#Check no. of dimensions of a tensor.
scalar.ndim

0

In [13]:
#create a vector
vector = tf.constant([1,3]);
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>

In [14]:
vector.ndim

1

In [15]:
#2nd order tensor
SOT = tf.constant([[1,3],[2,1]])
SOT

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 1]], dtype=int32)>

In [16]:
SOT.ndim

2

In [20]:
#we want to specify data type
ano_matrix = tf.constant([[0.4,1.1],[2.1,4.3],[1.2,0.8]], dtype = tf.float16)
ano_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[0.4, 1.1],
       [2.1, 4.3],
       [1.2, 0.8]], dtype=float16)>

In [21]:
ano_matrix.ndim

2